# Generated by Django 3.1.1 on 2020-09-21 18:56

from django.db import migrations, models
import weddinglist.managers


class Migration(migrations.Migration):

    dependencies = [
        ('weddinglist', '0001_gift_giftlist_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', weddinglist.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
