# Generated by Django 3.1.1 on 2020-09-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddinglist', '0002_gift_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlistitem',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift', to='weddinglist.gift'),
        ),
        migrations.AlterField(
            model_name='giftlistitem',
            name='gift_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list', to='weddinglist.giftlist'),
        ),
    ]
