# Generated by Django 3.1.1 on 2020-09-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddinglist', '0003_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlistitem',
            name='gift_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftlist', to='weddinglist.giftlist'),
        ),
        migrations.AlterField(
            model_name='giftlistitem',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
